# Generated by Django 5.2.8 on 2025-11-14 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Event Title')),
                ('description', models.TextField(verbose_name='Event Description')),
                ('date', models.DateField(verbose_name='Event Date')),
                ('location', models.CharField(max_length=200, verbose_name='Event Location')),
                ('start_time', models.TimeField(verbose_name='Event Start Time')),
                ('image', models.ImageField(upload_to='event_images/', verbose_name='Event Image')),
                ('is_active', models.BooleanField(default=True, verbose_name='Event Active')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Event Created At')),
            ],
            options={
                'verbose_name': 'Event',
                'verbose_name_plural': 'Events',
                'ordering': ['-date'],
            },
        ),
    ]
