# Generated by Django 5.2.8 on 2025-12-06 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='galleryimage',
            name='title',
            field=models.CharField(blank=True, max_length=200, verbose_name='Image Title'),
        ),
    ]
