# Generated by Django 5.2.8 on 2025-12-06 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0002_alter_galleryimage_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='galleryimage',
            name='full_image',
            field=models.ImageField(default='gallery_image/default.jpg', upload_to='gallery_image/', verbose_name='Full Image'),
        ),
    ]
