# Generated by Django 5.2.8 on 2025-11-16 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Chef',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Имя')),
                ('position', models.CharField(max_length=100, verbose_name='Должность')),
                ('bio', models.TextField(verbose_name='Биография')),
                ('image', models.ImageField(upload_to='chefs_images/', verbose_name='Фото')),
                ('experience', models.IntegerField(verbose_name='Опыт работы (лет)')),
                ('specialty', models.CharField(max_length=100, verbose_name='Специализация')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активный сотрудник')),
                ('order', models.IntegerField(default=0, verbose_name='Порядок отображения')),
            ],
            options={
                'verbose_name': 'Шеф-повар',
                'verbose_name_plural': 'Шеф-повара',
                'ordering': ['order', 'name'],
            },
        ),
    ]
