# Generated by Django 5.2.8 on 2025-12-16 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chefs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='chef',
            name='social_url_1',
            field=models.CharField(blank=True, max_length=100, verbose_name='Соцсеть'),
        ),
        migrations.AddField(
            model_name='chef',
            name='social_url_2',
            field=models.CharField(blank=True, max_length=100, verbose_name='Соцсеть'),
        ),
        migrations.AddField(
            model_name='chef',
            name='social_url_3',
            field=models.CharField(blank=True, max_length=100, verbose_name='Соцсеть'),
        ),
    ]
