# Generated by Django 5.2.8 on 2025-12-22 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='admin_notified',
            field=models.BooleanField(default=False, verbose_name='Администратор уведомлен'),
        ),
        migrations.AddField(
            model_name='reservation',
            name='email_sent',
            field=models.BooleanField(default=False, verbose_name='Email отправлен клиенту'),
        ),
    ]
