# Generated by Django 5.2.8 on 2025-12-01 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tag',
            name='slug',
            field=models.SlugField(blank=True, max_length=100, unique=True, verbose_name='URL tag'),
        ),
    ]
