# Generated by Django 5.2.8 on 2025-12-01 16:02

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_tag_slug'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='is_best',
            field=models.BooleanField(default=False, verbose_name='best post'),
        ),
        migrations.AddIndex(
            model_name='post',
            index=models.Index(fields=['is_best', '-created_at', 'is_published'], name='blog_post_is_best_43853f_idx'),
        ),
    ]
