# Generated by Django 5.2.8 on 2025-12-18 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='image',
            field=models.ImageField(default='reviews_images/default.png', upload_to='reviews_images/', verbose_name='Фото автора'),
        ),
    ]
