# Generated by Django 5.2.8 on 2026-01-03 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0002_alter_review_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='admin_notified',
            field=models.BooleanField(default=False, verbose_name='Администратор уведомлен'),
        ),
    ]
