# Generated by Django 5.2.8 on 2025-11-14 17:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Name category')),
                ('order', models.IntegerField(default=0, verbose_name='Order')),
            ],
            options={
                'verbose_name': 'Category',
                'verbose_name_plural': 'Categories',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='MenuItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Name item')),
                ('description', models.TextField(verbose_name='Description item')),
                ('ingredients', models.TextField(verbose_name='Ingredients')),
                ('price', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Price')),
                ('meal_type', models.CharField(choices=[('breakfast', 'Завтрак'), ('lunch', 'Обед'), ('dinner', 'Ужин'), ('any', 'Любое время')], default='any', max_length=30, verbose_name='Type')),
                ('image', models.ImageField(upload_to='menu_images/', verbose_name='Image')),
                ('calories', models.IntegerField(blank=True, null=True, verbose_name='Calories')),
                ('is_special', models.BooleanField(default=False, verbose_name='Special')),
                ('is_new', models.BooleanField(default=False, verbose_name='New')),
                ('cooking_time', models.IntegerField(blank=True, default=15, null=True, verbose_name='Cooking time')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='menu.category', verbose_name='Category')),
            ],
            options={
                'verbose_name': 'Menu item',
                'verbose_name_plural': 'Menu items',
                'ordering': ['category__order', 'name'],
            },
        ),
    ]
