# Generated by Django 5.2.8 on 2025-11-19 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menuitem',
            name='description',
            field=models.TextField(blank=True, verbose_name='Description item'),
        ),
        migrations.AlterField(
            model_name='menuitem',
            name='ingredients',
            field=models.TextField(blank=True, verbose_name='Ingredients'),
        ),
    ]
