# Generated by Django 5.2.8 on 2025-11-24 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0003_mealtype_alter_category_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='menuitem',
            name='meal_types',
        ),
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['order'], 'verbose_name': 'Category', 'verbose_name_plural': 'Categories'},
        ),
        migrations.AddField(
            model_name='menuitem',
            name='meal_type',
            field=models.CharField(blank=True, help_text='Можно указать несколько значений через запятую: Завтрак, Обед, Ужин...', max_length=100, verbose_name='Время приема пищи'),
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Name category'),
        ),
        migrations.AlterField(
            model_name='category',
            name='order',
            field=models.IntegerField(default=0, verbose_name='Order'),
        ),
        migrations.AlterField(
            model_name='menuitem',
            name='calories',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='menuitem',
            name='cooking_time',
            field=models.IntegerField(default=15),
        ),
        migrations.AlterField(
            model_name='menuitem',
            name='is_new',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='menuitem',
            name='is_special',
            field=models.BooleanField(default=False),
        ),
        migrations.DeleteModel(
            name='MealType',
        ),
    ]
