# Generated by Django 5.2.8 on 2025-11-25 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0004_remove_menuitem_meal_types_alter_category_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MealType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(choices=[('breakfast', 'Завтрак'), ('lunch', 'Обед'), ('dinner', 'Ужин'), ('any', 'Любое время')], max_length=20, unique=True)),
            ],
            options={
                'verbose_name': 'Тип блюда',
                'verbose_name_plural': 'Типы блюд',
            },
        ),
        migrations.RemoveField(
            model_name='menuitem',
            name='meal_type',
        ),
        migrations.AddField(
            model_name='menuitem',
            name='meal_types',
            field=models.ManyToManyField(blank=True, to='menu.mealtype', verbose_name='Тип блюда'),
        ),
    ]
