# Generated by Django 5.2.8 on 2025-12-09 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0006_category_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='menuitem',
            name='image_dish',
            field=models.ImageField(default='menu_images/default.png', upload_to='menu_images/'),
        ),
    ]
