# Generated by Django 5.2.8 on 2025-12-09 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0007_menuitem_image_dish'),
    ]

    operations = [
        migrations.AddField(
            model_name='menuitem',
            name='stop_list',
            field=models.BooleanField(default=False),
        ),
    ]
