# Generated by Django 5.2.8 on 2025-12-09 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0008_menuitem_stop_list'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menuitem',
            name='image',
            field=models.ImageField(blank=True, upload_to='menu_images/'),
        ),
    ]
