# Generated by Django 5.2.8 on 2025-12-13 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0009_alter_menuitem_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='image_background',
            field=models.ImageField(default='menu_images/default.png', upload_to='menu_images/'),
        ),
    ]
