# Generated by Django 5.2.8 on 2025-12-24 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0010_category_image_background'),
    ]

    operations = [
        migrations.AddField(
            model_name='menuitem',
            name='is_delivery',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='menuitem',
            name='image',
            field=models.ImageField(default='menu_images/default.png', upload_to='menu_images/'),
        ),
    ]
