# Generated by Django 5.2.8 on 2025-12-25 18:36

import django.core.validators
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('menu', '0011_menuitem_is_delivery_alter_menuitem_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Coupon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, unique=True, verbose_name='Код купона')),
                ('discount_percent', models.DecimalField(decimal_places=2, max_digits=5, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Процент скидки')),
                ('discount_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Фиксированная сумма скидки')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('valid_from', models.DateTimeField(verbose_name='Действует с')),
                ('valid_until', models.DateTimeField(verbose_name='Действует до')),
                ('max_uses', models.PositiveIntegerField(default=1, verbose_name='Максимум использований')),
                ('times_used', models.PositiveIntegerField(default=0, verbose_name='Использован раз')),
            ],
            options={
                'verbose_name': 'Купон',
                'verbose_name_plural': 'Купоны',
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('customer_name', models.CharField(max_length=100, verbose_name='Имя покупателя')),
                ('delivery_address', models.TextField(blank=True, null=True, verbose_name='Адрес доставки')),
                ('phone_number', models.CharField(max_length=20, verbose_name='Номер телефона')),
                ('status', models.CharField(choices=[('new', 'Новый'), ('confirmed', 'Подтвержден'), ('preparing', 'Готовится'), ('delivering', 'В доставке'), ('completed', 'Выполнен'), ('cancelled', 'Отменен')], default='new', max_length=20, verbose_name='Статус')),
                ('delivery_method', models.CharField(choices=[('courier', 'Курьер'), ('pickup', 'Самовывоз')], default='courier', max_length=20, verbose_name='Способ доставки')),
                ('payment_method', models.CharField(choices=[('cash', 'Наличные'), ('card', 'Банковская карта')], default='cash', max_length=20, verbose_name='Способ оплаты')),
                ('delivery_cost', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Стоимость доставки')),
                ('total_cost', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Общая стоимость (без скидки)')),
                ('discount', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Скидка')),
                ('final_cost', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Итоговая стоимость (к оплате)')),
                ('coupon_code', models.CharField(blank=True, max_length=50, null=True, verbose_name='Код купона')),
                ('is_confirmed', models.BooleanField(default=False, verbose_name='Подтвержден по SMS')),
                ('sms_code', models.CharField(blank=True, max_length=128, null=True, verbose_name='Код подтверждения (хэш)')),
                ('sms_code_sent_at', models.DateTimeField(blank=True, null=True, verbose_name='Код отправлен')),
            ],
            options={
                'verbose_name': 'Заказ',
                'verbose_name_plural': 'Заказы',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Количество')),
                ('price_at_order', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Цена на момент заказа')),
                ('dish_name', models.CharField(blank=True, max_length=200, verbose_name='Название блюда')),
                ('dish', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='order_items', to='menu.menuitem', verbose_name='Блюдо')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='orders.order', verbose_name='Заказ')),
            ],
            options={
                'verbose_name': 'Позиция заказа',
                'verbose_name_plural': 'Позиции заказа',
            },
        ),
    ]
